name: CI
on: 
    pull_request:
    push:
      branches:
        - master

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: marceloprado/has-changed-path@master
        id: backend-changed
        with:
          paths: svc

      - name: Integration tests
        if: steps.backend-changed.outputs.changed == 'true'
        run: |
          echo "running the integration tests"

      - name: Unit tests
        if: steps.backend-changed.outputs.changed == 'false'
        run: |
          echo "running the short tests"
      
  ui:
    name: UI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit tests
        if: steps.backend-changed.outputs.changed == 'false'
        run: |
          echo "running the short tests"
